{% set name = "mystmd" %}
{% set version = "1.1.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mystmd-{{ version }}.tar.gz
  sha256: 4ec83ea2ad37d25c23f8ef5af7cef7bbe8cfd4ca2b8da4dd68f1fd800fac8e86

build:
  entry_points:
    - myst = mystmd_py.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-nodejs-version
  run:
    - python >=3.8

test:
  imports:
    - mystmd_py
  commands:
    - pip check
    - myst --help
  requires:
    - pip
    - nodejs

about:
  home: https://github.com/executablebooks/mystmd
  summary: Command line tools for MyST Markdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agoose77
    - fwkoch
    - rowanc1
